- name: Jenkins Node Cleanup Playbook
  hosts: jenkins
  become: yes
  tasks:

    - name: Clean up Jenkins workspaces
      file:
        path: /var/lib/jenkins/workspace/
        state: absent
      tags: cleanup

    - name: Delete old builds
      shell: |
        find /var/lib/jenkins/jobs/ -type d -path "*/builds/*" -mtime +30 -exec rm -rf {} +
      tags: cleanup

    - name: Clean up Jenkins logs
      shell: |
        find /var/log/jenkins -type f -name "*.log" -exec truncate -s 0 {} \;
      tags: cleanup

    # - name: Remove unused plugins
    #   shell: |
    #     jenkins-cli -s http://localhost:8080/ -auth user:token uninstall-plugin {{ item }}
    #   loop: "{{ unused_plugins }}"
    #   when: unused_plugins is defined
    #   tags: cleanup

    - name: Docker system prune (if Docker is present)
      shell: docker system prune -a -f
      when: docker_present | bool
      tags: cleanup

    - name: Ensure /tmp directory exists
      file:
        path: /tmp/
        state: directory
        mode: '1777'
      tags: setup

    - name: Clear files in /tmp if directory exists
      shell: |
        if [ -d /tmp ]; then find /tmp -type f -delete; fi
      tags: cleanup

    - name: Clear /var/tmp files if directory exists
      shell: |
        if [ -d /var/tmp ]; then find /var/tmp -type f -delete; fi
      tags: cleanup

    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted
      tags: restart

  vars:
    docker_present: "{{ (ansible_facts.packages['docker'] is defined) or (ansible_facts.services['docker'] is defined) }}"
