- name: Prepare the Python virtualenv
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # RECENT CHANGE: force Ansible to use system Python3 for the following modules:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Create a virtual environment
      command: python3 -m venv /tmp/ansible_venv

    - name: Install pip requirements into the venv
      command: /tmp/ansible_venv/bin/pip install \
               google-auth jmespath requests \
               google-api-python-client \
               google-cloud-secret-manager

- name: Use the venv for all further tasks
  hosts: localhost
  connection: local
  vars:
    # RECENT CHANGE: now switch Ansible to the venv Python
    ansible_python_interpreter: /tmp/ansible_venv/bin/python

  # RECENT CHANGE: fact-gathering defaults to true meaning setup runs under the venv
  tasks:
    - name: Show the Python interpreter used by Ansible
      debug:
        var: ansible_python_interpreter