- name: Prepare the Python virtualenv
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # force Ansible to use system Python3 for all modules here
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Create a virtual environment
      command: python3 -m venv /tmp/ansible_venv

    - name: Install pip requirements into the venv
      command: /tmp/ansible_venv/bin/pip install \
               google-auth jmespath requests \
               google-api-python-client \
               google-cloud-secret-manager

- name: Use the venv for all further tasks
  hosts: localhost
  connection: local
  vars:
    # now switch Ansible to your new venv Python
    ansible_python_interpreter: /tmp/ansible_venv/bin/python

  # fact-gathering defaults to true, so setup will run under the venv
  tasks:
    - name: Show the Python interpreter used by Ansible
      debug:
        var: ansible_python_interpreter

    # …other tasks that need the installed libraries…